<!DOCTYPE html>
 <html lang="en">

<head>

    	<!-- Metas -->
        <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		<meta name="keywords" content="HTML5 Template Coco onepage themeforest" />
		<meta name="description" content="Code Makers Template" />
		<meta name="author" content="" />

		<!-- Title  -->
		<title>CodeMakex|<?= $this->title ?> </title>

		<!-- Favicon -->
		<link rel="shortcut icon" href="<?= $this->access('library/front/img/favicon.ico') ?>" />

		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900" rel="stylesheet">

		<!-- custom -->
		<link rel="stylesheet" href="<?= $this->access('asset/css/site.css') ?>" />
    </head>

    <body>
  

        homepage !
       
        <!-- javascripts -->
        <script src="<?= $this->access(' ') ?>"></script> 
    </body>

 </html>