



<div class="row">
    <div class="col-lg-8">


        <div class=" card bg-gradient-primary">

            <div class="col-lg-12" >

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

                    <div class="carousel-inner">

                        <div class="carousel-item active" style="min-height: 250px; ">
                            <h6 class="card-header">
                                <i class="fas fa-th mr-1"></i>
                                Pages Management
                            </h6>

                            <div class=" card-body col-lg-3">
                                <div class=" card bg-gradient-primary ">
                                    <center class="">
                                        <span class=""><i class="far fa-envelope"></i></span>
                                    </center>
                                    <center class="">
                                        <span class="info-box-text">Messages</span>
                                        <span class="info-box-number">1,410</span>
                                    </center>
                                </div>
                            </div>

                        </div>
                        <div class="carousel-item " style="min-height: 250px; ">
                            <h6 class="card-header">
                                <i class="fas fa-th mr-1"></i>
                                Appearance Management
                            </h6>

                            <div class="row">
                                <div class="card-body  col-lg-3">
                                    <div class=" card bg-gradient-primary btn btn-default" type="button"  data-toggle="modal" data-target="#modal-xl">
                                        <center class="">
                                            <span class=""><i class="far fa-envelope"></i></span>
                                        </center>
                                        <center class="">
                                            <span class="info-box-text">Menu</span>
                                        </center>
                                    </div>
                                </div>
                                <div class=" card-body  col-lg-3">
                                    <div class=" card bg-gradient-primary ">
                                        <center class="">
                                            <span class=""><i class="far fa-envelope"></i></span>
                                        </center>
                                        <center class="">
                                            <span class="info-box-text">Pages</span>
                                        </center>
                                    </div>
                                </div>
                                <div class=" card-body  col-lg-3">
                                    <div class=" card bg-gradient-primary ">
                                        <center class="">
                                            <span class=""><i class="far fa-envelope"></i></span>
                                        </center>
                                        <center class="">
                                            <span class="info-box-text">Page Layouts</span>
                                        </center>
                                    </div>
                                </div>

                                <div class=" card-body col-lg-3">
                                    <div class=" card bg-gradient-primary ">
                                        <center class="">
                                            <span class=""><i class="far fa-envelope"></i></span>
                                        </center>
                                        <center class="">
                                            <span class="info-box-text">Section Layouts</span>
                                        </center>
                                    </div>
                                </div>
                            </div>

                        </div>



                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        </ol>


                    </div>
                </div>





            </div>
            <!-- /.card-body -->
        </div>










        <!-- TO DO List -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="ion ion-clipboard mr-1"></i>
                    My recent posts
                </h3>

                <div class="card-tools">
                    <ul class="pagination pagination-sm">
                        <li class="page-item"><a href="#" class="page-link">&laquo;</a></li>
                        <li class="page-item"><a href="#" class="page-link">1</a></li>
                        <li class="page-item"><a href="#" class="page-link">2</a></li>
                        <li class="page-item"><a href="#" class="page-link">3</a></li>
                        <li class="page-item"><a href="#" class="page-link">&raquo;</a></li>
                    </ul>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <ul class="todo-list" data-widget="todo-list">
                    <li>
                        <!-- drag handle -->

                        <!-- checkbox -->
                        <div  class="icheck-primary d-inline ml-2">
                            <input type="checkbox" value="" name="todo1" id="todoCheck1">
                            <label for="todoCheck1"></label>
                        </div>
                        <!-- todo text -->
                        <span class="text">Design a nice theme</span>
                        <!-- Emphasis label -->
                        <small class="badge badge-danger"><i class="far fa-clock"></i> 2 mins</small>
                        <!-- General tools such as edit or delete-->
                        <div class="tools">
                            <i class="fas fa-edit"></i>
                            <i class="fas fa-trash-o"></i>
                        </div>
                    </li>
                    <li>
                        <!-- drag handle -->

                        <!-- checkbox -->
                        <div  class="icheck-primary d-inline ml-2">
                            <input type="checkbox" value="" name="todo1" id="todoCheck1">
                            <label for="todoCheck1"></label>
                        </div>
                        <!-- todo text -->
                        <span class="text">Design a nice theme</span>
                        <!-- Emphasis label -->
                        <small class="badge badge-danger"><i class="far fa-clock"></i> 2 mins</small>
                        <!-- General tools such as edit or delete-->
                        <div class="tools">
                            <i class="fas fa-edit"></i>
                            <i class="fas fa-trash-o"></i>
                        </div>
                    </li>
                    <li>
                        <!-- drag handle -->

                        <!-- checkbox -->
                        <div  class="icheck-primary d-inline ml-2">
                            <input type="checkbox" value="" name="todo1" id="todoCheck1">
                            <label for="todoCheck1"></label>
                        </div>
                        <!-- todo text -->
                        <span class="text">Design a nice theme</span>
                        <!-- Emphasis label -->
                        <small class="badge badge-danger"><i class="far fa-clock"></i> 2 mins</small>
                        <!-- General tools such as edit or delete-->
                        <div class="tools">
                            <i class="fas fa-edit"></i>
                            <i class="fas fa-trash-o"></i>
                        </div>
                    </li>

                    <li>

                        <div  class="icheck-primary d-inline ml-2">
                            <input type="checkbox" value="" name="todo2" id="todoCheck2" checked>
                            <label for="todoCheck2"></label>
                        </div>
                        <span class="text">Make the theme responsive</span>
                        <small class="badge badge-info"><i class="far fa-clock"></i> 4 hours</small>
                        <div class="tools">
                            <i class="fas fa-edit"></i>
                            <i class="fas fa-trash-o"></i>
                        </div>
                    </li>
                    <li>
                        <div  class="icheck-primary d-inline ml-2">
                            <input type="checkbox" value="" name="todo3" id="todoCheck3">
                            <label for="todoCheck3"></label>
                        </div>
                        <span class="text">Let theme shine like a star</span>
                        <small class="badge badge-warning"><i class="far fa-clock"></i> 1 day</small>
                        <div class="tools">
                            <i class="fas fa-edit"></i>
                            <i class="fas fa-trash-o"></i>
                        </div>
                    </li>


                </ul>
            </div>
        </div>
        <!-- /.card -->




        <!-- START CAROUSEL-->
        <h5 class="mt-4 mb-2">Bootstrap Accordion & Carousel</h5>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Carousel</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            gdfgf
                        </div>
                        <div class="carousel-item">

                        </div>
                        <div class="carousel-item">

                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

        <!-- /.row -->





    </div>









    <!-- /.col-md-4 -->
    <div class="col-lg-4">


        <a href="<?= $this->path('admin.news.create') ?>" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            Create Article
        </a>

        <br/>
        <br/>

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Actions</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item active">
                        <a href="#" class="nav-link">
                            <i class="fas fa-inbox"></i> Draft
                            <span class="badge bg-primary float-right">12</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-envelope"></i> Sent for vetting
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-file-alt"></i> Posted
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-trash-alt"></i> Trash
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.card-body -->
        </div>








        <div class="card card-primary card-outline">
            <div class="card-header">
                <h5 class="card-title m-0"> Recent postings on per categories</h5>
            </div>
            <div class="card-body">


                <ul class="nav nav-pills flex-column">
                    <li class="nav-item active">
                        <a href="#" class="nav-link">
                            <i class="fas fa-inbox"></i> Breaking news
                            <span class="badge bg-primary float-right">12</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-envelope"></i> Top stories
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-file-alt"></i> Economy
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-trash-alt"></i> Innovation
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    </div>
    <!-- /.col-md-6 -->
</div>




<!--Modals-->
<!-- /.modal -->

      <div class="modal fade" id="modal-xl">
        <div class="modal-dialog modal-xl">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Menu Management</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer justify-content-between">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->















