
<!-- Outer Row -->
<div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <a  class="col-lg-6 d-none d-lg-block " href="<?= $this->path('site.index') ?>" >
                        <img class="" src="<?= $this->access('asset/img/logo/fruit-vector.png') ?>" alt="" style="max-height:  350px"/>

                    </a>
                    <!--<div class="col-lg-6 d-none d-lg-block bg-login-image"></div>-->
                    <div class="col-lg-6">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Welcome To Login Page !</h1>
                            </div>
                            <form class="user" method="post" action="<?= $this->path('adm.login.check') ?>">
                                <div class="form-group">
                                    <input type="username" name="username" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Username...">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                                </div>
                                <div class="form-group">
                                    <div class="custom-control custom-checkbox small">
                                        <input type="checkbox" class="custom-control-input" id="customCheck">
                                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary btn-user btn-block">
                                    Login
                                </button>

                            </form>
                            <hr>

                            <?php if ($this->hasErrors()) { ?>
                                <div class="alert custom alert-danger alert-dismissable ">
                                    <button type="button" class="close text-center " data-dismiss="alert" aria-hidden="true">&times;</button>
                                    <?= implode('|', $this->getErrors()) ?>
                                </div>
                            <?php } ?>

                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>























