<h3 class="page-header top-stories pl-4 py-2 text-uppercase">Top Stories</h3>

<div class="row" >
    <!-- Lead Story -->
    <img src="images/qi1.jpg" alt="" class="pr-md-0 col-md-8">
    <div class="col-md-4 pt-md-5 px-md-4" >
        <div class="page-header ">
            General news
        </div>
        <a href="#" class="nav-link">Govt to claw back GH¢300 million monthly at the ports -Franklin Cudjoe, President, IMANI Africa </a>
        <p>The government could claw back GH¢300 million monthly, following its intention to reverse its policy on reduced</p>
    </div>
</div>

<div class="row pt-4">
    <div class="col-md-6 col-xm-12 pr-2">
        <div class="row ">
            <img src="images/qi1.jpg" alt="news1" class="img-rounded col-md-4">

            <div class="col-md-8">
                <a href="#">
                    <p class="lead">Do not pay any fee for stimulus package registration – NBSSI cautions applicants</p>
                </a>

            </div>
        </div>
    </div>

    <div class="col-md-6 col-xm-12 pr-md-2">
        <div class="row ">
            <img src="images/qi1.jpg" alt="news1" class="img-rounded col-md-4">

            <div class="col-md-8">
                <a href="#">
                    <p class="lead">Do not pay any fee for stimulus package registration – NBSSI cautions applicants</p>
                </a>

            </div>
        </div>
    </div>
</div>

<div class="row pt-4">
    <div class="col-md-6 col-xm-12 pr-2">
        <div class="row ">
            <img src="images/qi1.jpg" alt="news1" class="img-rounded col-md-4">

            <div class="col-md-8">
                <a href="#">
                    <p class="lead">Do not pay any fee for stimulus package registration – NBSSI cautions applicants</p>
                </a>

            </div>
        </div>
    </div>

    <div class="col-md-6 col-xm-12 pr-md-2">
        <div class="row ">
            <img src="images/qi1.jpg" alt="news1" class="img-rounded col-md-4">

            <div class="col-md-8">
                <a href="#">
                    <p class="lead">Do not pay any fee for stimulus package registration – NBSSI cautions applicants</p>
                </a>

            </div>
        </div>
    </div>
</div>

<!-- Watch / Listen portion -->
<div class="row my-4">
    <div class="col-md-6 pt-3">
        <h4 class="lead" style="color: red;"> <b>Watch</b> </h4>
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="images/video.mp4" allowfullscreen>
                Your browser does not support the HTML5 Video element.
            </iframe>
        </div>
    </div>
    <div class="col-md-6 pt-3">
        <h4 class="lead" style="color: red;"> <b>Listen</b> </h4>
        <audio controls="controls" src="images/audio.mp3" style="background-image: url('images/qi1.jpg');">
            Your browser does not support the HTML5 Audio element.
        </audio>
    </div>
</div>

<h4 class="lead text-uppercase">General News</h4>
<div class="row mb-4">
    <img src="images/qi13.jpg" alt="" class="col-md-4">
    <div class="col-md-8">
        <div class="lead">
            <b>
                COVID-19 test results of MPs won’t be made public – Medical Services Director
            </b>
        </div>
        <span class="py-5">By Edem NYONATOR </span>
        <p>
            <a href="#">The Director of Medical Services in Parliament, Dr Prince Pambo has said the COVID-19 test results of Members of Parliament...</a>
        </p>
    </div>
</div>

<h4 class="lead text-uppercase">Economy</h4>
<div class="row mb-4">
    <img src="images/qi13.jpg" alt="" class="col-md-4">
    <div class="col-md-8">
        <div class="lead">
            <b>
                COVID-19 test results of MPs won’t be made public – Medical Services Director
            </b>
        </div>
        <span class="py-5">By Edem NYONATOR </span>
        <p>
            <a href="#">The Director of Medical Services in Parliament, Dr Prince Pambo has said the COVID-19 test results of Members of Parliament...</a>
        </p>
    </div>
</div>